import { PropTypes } from 'react';

const shape = PropTypes.shape;
const string = PropTypes.string;

const phrases = {
  en: {
    vehicle_name: 'Vehicle Name',
    license: 'License Plate Number',
    imei: 'IMEI',
    manufacturer: 'Manufacturer',
    odo_in_miles: 'ODO value in miles',
    model_name: 'Model Name',
    year: 'Year of Manufacture',
    odometer_value: 'Odometer (km.)',
    vehicle_kind_hint: 'Kind of the Vehicle',
    // sending: 'sending',
    save: 'Save',
    cancel: 'Cancel',

    undefined: 'Undefined',
    boat: 'Vessel',
    farm: 'Farm implementation',
    forklift: 'Forklift',
    hgv: 'Heavy Goods Vehicle',
    hgv_chilled: 'Heavy Goods Vehicle Chilled',
    hgv_frozen: 'Heavy Goods Vehicle Frozen',
    mgv: 'Medium Goods Vehicle',
    mgv_chilled: 'Medium Goods Vehicle Chilled',
    mgv_frozen: 'Medium Goods Vehicle Frozen',
    mini_bus: 'Minibus',
    motorcycle: 'Motorcycle',
    passenger_car: 'Passenger Car',
    pick_up: 'Pickup',
    sgv: 'Small Goods Vehicle',
    sgv_chilled: 'Small Goods Vehicle Chilled',
    sgv_frozen: 'Small Goods Vehicle Frozen',
    suv: 'SUV',
    taxi: 'Taxi',
    tractor: 'Traktor',
  },

  th: {
    vehicle_name: 'ชื่อยานพาหนะ',
    license: 'เลขทะเบียน',
    imei: 'IMEI',
    manufacturer: 'ผู้ผลิต',
    odo_in_miles: 'มาตรวัดระยะทางในหน่วยไมล์',
    model_name: 'รุ่น',
    year: 'ปีที่ผลิต',
    odometer_value: 'มาตรวัดระยะทาง (กิโลเมตร)',
    vehicle_kind_hint: 'ประเภทของยานพาหนะ',
    // sending: 'sending',
    save: 'บันทึก',
    cancel: 'ยกเลิก',

    undefined: 'ไม่กำหนด',
    boat: 'เรือ',
    farm: 'รถฟาร์ม',
    forklift: 'โฟล์คลิฟท์',
    hgv: 'รถบรรทุกขนาดใหญ่',
    hgv_chilled: 'รถบรรทุกขนาดใหญ่แช่เย็น',
    hgv_frozen: 'รถบรรทุกขนาดใหญ่แช่แข็ง',
    mgv: 'รถบรรทุกขนาดกลาง',
    mgv_chilled: 'รถบรรทุกขนาดกลางแช่เย็น',
    mgv_frozen: 'รถบรรทุกขนาดกลางแช่แข็ง',
    mini_bus: 'มินิบัส',
    motorcycle: 'รถจักรยานยนต์',
    passenger_car: 'รถยนต์นั่ง',
    pick_up: 'รถกระบะ',
    sgv: 'รถบรรทุกขนาดเล็ก',
    sgv_chilled: 'รถบรรทุกขนาดเล็กแช่เย็น',
    sgv_frozen: 'รถบรรทุกขนาดเล็กแช่แข็ง',
    suv: 'รถตรวจการ',
    taxi: 'แท็กซี่',
    tractor: 'แทร็กเตอร์',
  },
};

export const phrasesShape = shape({
  vehicle_name: string.isRequired,
  license: string.isRequired,
  imei: string.isRequired,
  manufacturer: string.isRequired,
  odo_in_miles: string.isRequired,
  model_name: string.isRequired,
  year: string.isRequired,
  odometer_value: string.isRequired,
  // sending: string.isRequired,
  save: string.isRequired,
  cancel: string.isRequired,
  vehicle_kind_hint: string.isRequired,

  undefined: string.isRequired,
  boat: string.isRequired,
  farm: string.isRequired,
  forklift: string.isRequired,
  hgv: string.isRequired,
  hgv_chilled: string.isRequired,
  hgv_frozen: string.isRequired,
  mgv: string.isRequired,
  mgv_chilled: string.isRequired,
  mgv_frozen: string.isRequired,
  mini_bus: string.isRequired,
  motorcycle: string.isRequired,
  passenger_car: string.isRequired,
  pick_up: string.isRequired,
  sgv: string.isRequired,
  sgv_chilled: string.isRequired,
  sgv_frozen: string.isRequired,
  suv: string.isRequired,
  taxi: string.isRequired,
  tractor: string.isRequired,
});

export default phrases;
