export default [
  'alerts',
  'loading',
  'maintenance',
  'no_alerts',
  'alerts',
  'on_enter_location',
  'on_exit_location',
  'reset',
  'add',
  'fuel_alert',
  'fuel_gain_alert',
  'fuel_loss_alert',
  'engine_temp_alert',
  'service_frequency',
];
